(: from a csv of postags, create cite inventory for Latin morphology :)
(: read from the Github repository :)
let $i := file:read-text("https://github.com/nevenjovanovic/croala-pelagios/raw/master/csv/citeposlist.csv")
let $csv := csv:parse($i)
return db:create("cp-latmorph", $csv, "latmorph")
(: return $csv :)